backend:
  name: github
  repo: saylaan/GatsbyCommerce_2019

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

collections:
  - name: shop
    label: Shop
    folder: content/shop
    create: true
    fields:
      - { name: date, label: Date, widget: date, required: true }
      - { name: title, label: Title, widget: string, required: false }
      - { name: id, label: Id, widget: number, required: true, valueType: int }
      - { name: name, label: Name, widget: string, required: true }
      - { name: categorie, label: Categorie, widget: string, required: true }
      - { name: description, label: Description, widget: text, required: true }
      - { name: price, label: Price, widget: number, default: 0, valueType: float }
      - { name: itemcount, label: ItemCount, widget: number, default: 100, valueType: int }
      - { name: path, label: Path, widget: string, required: true}
      - { name: gallery, label: Gallery, widget: list, required: true, field: {name: image, label: Image, widget: image, required: true } }
      - { name: body, label: Body, widget: markdown, required: false }
  - name: homePage
    label: homePage
    folder: content/homePage
    create: true
    fields:
      - { name: title, label: Title, widget: string, required: false }
      - { name: name, label: Name, widget: string, required: true }
      - { name: description, label: Description, widget: text, required: true }
      - { name: path, label: Path, widget: string, required: true}
      - { name: gallery, label: Gallery, widget: list, required: true, field: {name: image, label: Image, widget: image, required: true } }